main:
BIR Doctoral Consortium 2025 in Riga, Latvia (as an author)
IEEE CSR 2024 in London, UK (as an author)
ICALP LiCS FSCD 2024 in Tallinn, Estonia (as a volunteer)
IC3IT 2024 in Batna, Algeria (as a guest)
ACM SAC 2023 in Tallinn, Estonia (as a student)
