main:

  Conference Reviewers:
    
      - title: 2025 IEEE International Conference on Cyber Security and Resilience (IEEE CSR 2025)
        link: https://www.ieee-csr.org/

  Journal Reviewers:

      - title: IEEE Open Journal of the Communications Society
        link: https://www.comsoc.org/publications/journals/ieee-ojcoms
