main:

BIR 2025 at Riga, Latvia (as an author in the doctoral consortium)
IEEE CSR 2024 at London, UK (as an author)
ICALP LiCS FSCD 2024 at Tallinn, Estonia (as a volunteer)
IC3IT 2024 at Batna, Algeria (as a guest)
ACM SAC 2023 at Tallinn, Estonia (as a student)
