main:

- title: BIR 2025 at Riga, Latvia (as a author in the doctoral consortium)
- title: IEEE CSR 2024 at London, UK (as an author)
- title: ICALP LiCS FSCD 2024 at Tallinn, Estonia (as a volunteer)
- title: IC3IT 2024 at Batna, Algeria (as a guest)
- title: ACM SAC 2023 at Tallinn, Estonia (as a student)
